use sha2::{Digest, Sha256};
use std::sync::OnceLock;

/// One embedded migration file.
#[derive(Debug, Clone)]
pub struct Migration {
    pub version: i64,
    /// The file name, e.g. `0001_initial.sql`.
    pub name: &'static str,
    pub bytes: &'static [u8],
    /// Lowercase hex sha256 of `bytes`.
    pub checksum: String,
}

/// (version, file name, bytes), generated by build.rs from the repository's migrations/ directory.
const EMBEDDED: &[(i64, &str, &[u8])] = include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

pub fn hex(bytes: &[u8]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(DIGITS[(b >> 4) as usize] as char);
        out.push(DIGITS[(b & 15) as usize] as char);
    }
    out
}

pub fn checksum(bytes: &[u8]) -> String {
    hex(&Sha256::digest(bytes))
}

/// The migrations this build knows, in version order.
pub fn migrations() -> &'static [Migration] {
    static ALL: OnceLock<Vec<Migration>> = OnceLock::new();
    ALL.get_or_init(|| {
        EMBEDDED
            .iter()
            .map(|&(version, name, bytes)| Migration {
                version,
                name,
                bytes,
                checksum: checksum(bytes),
            })
            .collect()
    })
}

/// The highest migration version this build knows.
pub fn max_embedded_migration() -> i64 {
    migrations().last().map_or(0, |m| m.version)
}
